FROM golang:1.23.6-alpine as builder

WORKDIR /app

COPY go.mod go.sum .

RUN go mod download && go mod verify

RUN go install github.com/air-verse/air@latest

RUN go install -tags 'postgres,mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

USER 1000:1000

COPY . .

RUN go build -o bin/main .

FROM alpine:3.12

WORKDIR /app

COPY --from=builder /app/bin/main .

CMD ["./main"]