services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    environment:
      APP_URL: ${APP_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE: ${DATABASE}
    networks:
      - myapp
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - myapp
networks:
  myapp:
    driver: bridge